[build]
# Use simplified Railway Dockerfile
builder = "DOCKERFILE"
dockerfilePath = "config/docker/Dockerfile.railway"

[deploy]
# Start command for the FastAPI server - let Dockerfile handle this
# startCommand = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"

[service.main]
# Health check endpoint
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
# Environment variables that Railway will set
PORT = 8000
DATABASE_URL = "/app/data/events/events.duckdb"
CORS_ORIGINS = "*"
API_HOST = "0.0.0.0"
PYTHONPATH = "/app"